version: '3.8'

services:
  web:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./dist:/usr/share/nginx/html
    restart: always
